import Head from 'next/head'
import Image from 'next/image'
import { useEffect, useState } from 'react';
import styles from '../styles/Home.module.css'

export default function Home() {

  const[ContractAddress,SetContractAddress] = useState("");
  const[Provider,SetProvider] = useState("");
  const[VaribaleName,SetVariableName] = useState("");
  const[Output,SetOutput] = useState("");


  function HandleContractAddress(inputAddress:string){
    SetContractAddress(inputAddress)
    // console.log(ContractAddress)
  }

  useEffect(() => {
    // slotReader = new SlotReader(Provider,ContractAddress)
    // console.log(slotReader)
    // slotReader.test()
}, 
[ContractAddress,Provider,Output,[]]);

  function HandleProvider(inputProvider:string){
  SetProvider(inputProvider)
  // console.log(Provider)
  }

  function HandleVariableName(inputVaribaleName:string){
    SetVariableName(inputVaribaleName)
    // console.log(Provider)
    }

   function call () {
    SetOutput("hi")
   } 
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
      <h1 className={styles.title}> Starknet Contract variable Reader</h1>
      <div className={styles.card}>
              <h2> Enter the details </h2> <br/>
                  <label>Contract Address </label>
                  <input  type="text" name="name"  onChange={e => 
                        HandleContractAddress (e.target.value)} ></input>
                <br/><br/>

                <label>Provider Network </label>
                  <select  name="vars" value={Provider} onChange={e => 
                      HandleProvider(e.target.value)} >
                      <option value= "uint">Mainnet</option>
                      <option value= "string">Testnet</option>
                    </select>
                <br/><br/>

                <label>Variable name</label>
                  <input  type="text" name="name" value={VaribaleName} onChange={e => 
                      HandleVariableName(e.target.value)} />
                <br/><br/>

              <button className={styles.card} onClick={() => call()}>Fetch value</button>
              <div >
                    {Output}
              </div>
            </div>
     
    </main>
    </div>
  )
}
